<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ApplicationIcon>Assets\movie.ico</ApplicationIcon>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<AssemblyTitle>Movie</AssemblyTitle>
		<BuiltInComInteropSupport>true</BuiltInComInteropSupport>
		<AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
		<Version>$([System.DateTime]::UtcNow.ToString(yyyy.M.d.H))-develop</Version>
		<Authors>Sebastian Walter</Authors>
		<Company>evilbaschdi (Sebastian Walter)</Company>
		<Product>Movie</Product>
		<Copyright>Copyright © 2014 - $([System.DateTime]::UtcNow.ToString(yyyy)) evilbaschdi</Copyright>
		<LangVersion>preview</LangVersion>
		<PackageProjectUrl>https://github.com/evilbaschdi/movies</PackageProjectUrl>
		<RepositoryUrl>https://github.com/evilbaschdi/movies</RepositoryUrl>
		<PackageIconUrl>https://github.com/evilbaschdi/Movies/blob/master/Movie/movie.ico</PackageIconUrl>
		<PublishSingleFile>true</PublishSingleFile>
		<!-- ReSharper disable once UnknownProperty -->
		<DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(MSBuildProjectName).xml</DocumentationFile>
		<EnableNETAnalyzers>true</EnableNETAnalyzers>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<!--This helps with theme dll-s trimming.
	If you will publish your application in self-contained mode with p:PublishTrimmed=true and it will use Fluent theme Default theme will be trimmed from the output and vice versa.
	https://github.com/AvaloniaUI/Avalonia/issues/5593 -->
		<TrimmableAssembly Include="Avalonia.Themes.Fluent" />
		<TrimmableAssembly Include="Avalonia.Themes.Default" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="EvilBaschdi.Core.Avalonia.Mvvm.Command" />
		<Using Include="ReactiveUI.Primitives" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="EvilBaschdi.About.Avalonia" />
		<PackageReference Include="EvilBaschdi.Core.Avalonia" />
		<PackageReference Include="FluentAvaloniaUI" />
		<!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
		<PackageReference Include="AvaloniaUI.DiagnosticsSupport" Condition="'$(Configuration)' == 'Debug'" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Movie.Core\Movie.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<AvaloniaResource Include="Assets\**" />
		<Content Include="Assets\about.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Resource Include="Assets\movie.ico">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
	</ItemGroup>

</Project>
